mkdir project
cd project
touch  README.md
touch LICENSE.md
touch CITATION.md
touch CONTRIBUTION.md
touch CONDUCT.md
mkdir data
mkdir results
mkdir doc
mkdir src
mkdir from_joe
mkdir bin
cd doc
touch manuscript.md
cd ..
cd results
mkdir cleaned_data
mkdir simulated_data
mkdir final_results
mkdir intermediate_results
